SELECT PIZZA_NAME,
	PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM MENU
	LEFT JOIN PERSON_ORDER ON PERSON_ORDER.MENU_ID = MENU.ID
	JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
WHERE PERSON_ORDER.ID IS NULL
ORDER BY 1,
	2;