SELECT MISSING_DATE::DATE
FROM GENERATE_SERIES('2022-01-01'::DATE, '2022-01-10'::DATE, '1 day') AS MISSING_DATE
WHERE MISSING_DATE NOT IN 
	(SELECT VISIT_DATE FROM PERSON_VISITS
		WHERE PERSON_ID = 1 OR PERSON_ID = 2);