INSERT INTO PERSON_DISCOUNTS (ID, PERSON_ID, PIZZERIA_ID, DISCOUNT)
SELECT ROW_NUMBER() OVER () AS ID,
    PERSON_ID,
    MENU.PIZZERIA_ID AS PIZZERIA_ID,
    CASE
        WHEN COUNT(PERSON_ORDER.ID) = 1 THEN 10.5
        WHEN COUNT(PERSON_ORDER.ID) = 2 THEN 22
        ELSE 30
    END AS DISCOUNT
FROM PERSON_ORDER
    JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
GROUP BY PERSON_ID,
    PIZZERIA_ID