SELECT PIZZA_NAME,
	PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME,
	VISIT_DATE
FROM MENU
	JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
	JOIN PERSON_VISITS ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
WHERE PERSON_ID = 3
	AND PRICE BETWEEN 800 AND 1000
ORDER BY 1,
	2,
	3;