SELECT PIZZA_NAME, PIZZERIA.NAME AS PIZZERIA_NAME
FROM MENU
	JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
	JOIN PERSON_ORDER ON PERSON_ORDER.MENU_ID = MENU.ID
WHERE PERSON_ID IN (1, 4)
ORDER BY 1, 2;