WITH PIZ AS (
    SELECT PERSON.GENDER,
        PIZZERIA.NAME AS PIZZERIA_NAME
    FROM PERSON_ORDER
        LEFT JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID
        LEFT JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
        LEFT JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
) (
    SELECT PIZZERIA_NAME
    FROM PIZ
    EXCEPT
    SELECT PIZZERIA_NAME
    FROM PIZ
    WHERE GENDER = 'male'
)
UNION
(
    SELECT PIZZERIA_NAME
    FROM PIZ
    EXCEPT
    SELECT PIZZERIA_NAME
    FROM PIZ
    WHERE GENDER = 'female'
)
ORDER BY 1;