SELECT P.ADDRESS AS ADDRESS,
    PZ.NAME AS NAME,
    COUNT(*) AS COUNT_OF_ORDER
FROM PERSON_ORDER PO
    JOIN PERSON P ON P.ID = PO.PERSON_ID
    JOIN MENU M ON M.ID = PO.MENU_ID
    JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID
GROUP BY P.ADDRESS,
    PZ.NAME
ORDER BY 1,
    2;