SELECT P.NAME AS NAME,
    COUNT(*) AS COUNT_OF_ORDER,
    ROUND(AVG(M.PRICE), 2) AS AVERAGE_PRICE,
    MAX(M.PRICE) AS MAX_PRICE,
    MIN(M.PRICE) AS MIN_PRICE
FROM PERSON_ORDER PO
    JOIN MENU M ON M.ID = PO.MENU_ID
    JOIN PIZZERIA P ON P.ID = M.PIZZERIA_ID
GROUP BY NAME
ORDER BY 1;