WITH PIZ AS (
	SELECT PERSON.GENDER,
		PIZZERIA.NAME AS PIZZERIA_NAME
	FROM PERSON_VISITS
		LEFT JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
		LEFT JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
) (
	SELECT PIZZERIA_NAME
	FROM PIZ
	WHERE GENDER = 'male'
	EXCEPT ALL
	SELECT PIZZERIA_NAME
	FROM PIZ
	WHERE GENDER = 'female'
)
UNION ALL
(
	SELECT PIZZERIA_NAME
	FROM PIZ
	WHERE GENDER = 'female'
	EXCEPT ALL
	SELECT PIZZERIA_NAME
	FROM PIZ
	WHERE GENDER = 'male'
)
ORDER BY 1;