--Session 1
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--Session 2
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--Session 1
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
--Session 2
UPDATE PIZZERIA
SET RATING = 3.0
WHERE NAME = 'Pizza Hut';
COMMIT;
--Session 1
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
COMMIT;
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
--Session 2
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';