WITH PO AS (
    SELECT PIZZERIA.NAME,
        COUNT(*) AS COUNT
    FROM PERSON_ORDER
        JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
        JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
    GROUP BY PIZZERIA.NAME
),
PV AS (
    SELECT PIZZERIA.NAME,
        COUNT(*) AS COUNT
    FROM PERSON_VISITS
        JOIN PIZZERIA ON PIZZERIA.ID = PERSON_VISITS.PIZZERIA_ID
    GROUP BY PIZZERIA.NAME
),
PO_PV AS (
    SELECT PO.NAME,
        (PO.COUNT + PV.COUNT) AS TOTAL_COUNT
    FROM PO
        JOIN PV ON PV.NAME = PO.NAME
)
SELECT PIZZERIA.NAME,
    CASE
        WHEN TOTAL_COUNT IS NULL THEN 0
        ELSE TOTAL_COUNT
    END TOTAL_COUNT
FROM PIZZERIA
    FULL JOIN PO_PV ON PO_PV.NAME = PIZZERIA.NAME
ORDER BY 2 DESC,
    1;