--Session 1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
--Session 2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
--Session 1
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
--Session 2
UPDATE PIZZERIA
SET RATING = 3.6
WHERE NAME = 'Pizza Hut';
COMMIT;
--Session 1
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
COMMIT;
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';
--Session 2
SELECT *
FROM PIZZERIA
WHERE NAME = 'Pizza Hut';