SELECT NAME AS PIZZERIA_NAME
FROM PIZZERIA
	JOIN PERSON_VISITS ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
	JOIN MENU ON MENU.PIZZERIA_ID = PIZZERIA.ID
WHERE PERSON_ID = 9 AND VISIT_DATE = '2022-01-08' AND PRICE < 800;