--Session 1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
--Session 2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
--Session 1
SELECT SUM(RATING)
FROM PIZZERIA;
--Session 2
INSERT INTO PIZZERIA (ID, NAME, RATING)
VALUES (10, 'Kazan Pizza', 5);
COMMIT;
--Session 1
SELECT SUM(RATING)
FROM PIZZERIA;
COMMIT;
SELECT SUM(RATING)
FROM PIZZERIA;
--Session 2
SELECT SUM(RATING)
FROM PIZZERIA;