SELECT PERSON_ORDER.ORDER_DATE, 
	CONCAT(NAME, ' (age:', AGE, ')') AS PERSON_INFORMATION
FROM PERSON
	JOIN PERSON_ORDER ON PERSON_ORDER.PERSON_ID = PERSON.ID
ORDER BY ORDER_DATE, PERSON_INFORMATION;