CREATE TABLE PERSON_AUDIT (
    CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TYPE_EVENT CHAR(1) NOT NULL DEFAULT 'I' CONSTRAINT CH_TYPE_EVENT CHECK (TYPE_EVENT IN ('I', 'U', 'D')),
    ROW_ID BIGINT NOT NULL,
    NAME VARCHAR,
    AGE INTEGER,
    GENDER VARCHAR,
    ADDRESS VARCHAR
);
-----
CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT () RETURNS TRIGGER AS $$ BEGIN
INSERT INTO PERSON_AUDIT
VALUES (NOW(), 'I', NEW.*);
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
-----
CREATE TRIGGER TRG_PERSON_INSERT_AUDIT
AFTER
INSERT ON PERSON FOR EACH ROW EXECUTE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT ();
-----
INSERT INTO PERSON (ID, NAME, AGE, GENDER, ADDRESS)
VALUES (10, 'Damir', 22, 'male', 'Irkutsk');