CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT () RETURNS TRIGGER AS $$ BEGIN
INSERT INTO PERSON_AUDIT
VALUES (NOW(), 'D', OLD.*);
RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;
-----
CREATE TRIGGER TRG_PERSON_DELETE_AUDIT
AFTER DELETE ON PERSON FOR EACH ROW EXECUTE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT ();
-----
DELETE FROM PERSON
WHERE ID = 10;