SELECT PERSON.NAME AS NAME,
    PIZZA_NAME,
    PRICE,
    CAST(
        ((100 - PERSON_DISCOUNTS.DISCOUNT) / 100) * PRICE AS FLOAT
    ) AS DISCOUNT_PRICE,
    PIZZERIA.NAME AS PIZZERIA_NAME
FROM MENU
    JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
    JOIN PERSON_DISCOUNTS ON PERSON_DISCOUNTS.PIZZERIA_ID = PIZZERIA.ID
    JOIN PERSON ON PERSON.ID = PERSON_DISCOUNTS.PERSON_ID
ORDER BY 1,
    2;