SELECT
	COALESCE(PERSON.NAME, '-') AS PERSON_NAME,
	COALESCE(V.VISIT_DATE),
	COALESCE(PIZZERIA.NAME, '-') AS PIZZERIA_NAME
FROM
	(SELECT PERSON_ID, VISIT_DATE, PIZZERIA_ID FROM PERSON_VISITS
		WHERE VISIT_DATE BETWEEN '2022-01-01' AND '2022-01-03') AS V
	FULL JOIN PERSON ON PERSON.ID = V.PERSON_ID
	FULL JOIN PIZZERIA ON PIZZERIA.ID = V.PIZZERIA_ID
ORDER BY 1, 2, 3;