WITH DATES AS (SELECT DATES FROM
	GENERATE_SERIES('2022-01-01'::DATE, '2022-01-10'::DATE, '1 day') AS DATES)
	
SELECT DATES::DATE AS MISSING_DATE FROM DATES
WHERE DATES NOT IN 
	(SELECT VISIT_DATE FROM PERSON_VISITS
		WHERE PERSON_ID = 1 OR PERSON_ID = 2);