CREATE FUNCTION FNC_FIBONACCI (PSTOP INTEGER DEFAULT 10) RETURNS TABLE (NUM INTEGER) AS $$
DECLARE A INTEGER := 0;
B INTEGER := 1;
BEGIN NUM := A;
RETURN NEXT;
NUM := B;
RETURN NEXT;
WHILE a + B < PSTOP LOOP NUM := A + B;
A := B;
B := NUM;
RETURN NEXT;
END LOOP;
END;
$$ LANGUAGE PLPGSQL;
-----
SELECT *
FROM FNC_FIBONACCI (100);
SELECT *
FROM FNC_FIBONACCI ();