WITH MONEY_SUM AS (
    SELECT USER_ID,
        TYPE,
        CURRENCY_ID,
        SUM(MONEY) AS VOLUME
    FROM BALANCE
    GROUP BY 1,
        2,
        3
),
LATEST_CURRENCY_UPDATE AS (
    SELECT ID,
        MAX(UPDATED) AS MAX_UPDATED
    FROM CURRENCY
    GROUP BY 1
),
LATEST_CURRENCY AS (
    SELECT CY.ID,
        CY.NAME AS CURRENCY_NAME,
        CY.RATE_TO_USD
    FROM CURRENCY CY
        JOIN LATEST_CURRENCY_UPDATE LCU ON CY.ID = LCU.ID
        AND CY.UPDATED = LCU.MAX_UPDATED
)
SELECT COALESCE(USR.NAME, 'not defined') AS NAME,
    COALESCE(USR.LASTNAME, 'not defined') AS LASTNAME,
    MS.TYPE,
    MS.VOLUME,
    COALESCE(LC.CURRENCY_NAME, 'not defined') AS CURRENCY_NAME,
    COALESCE(LC.RATE_TO_USD, 1) AS LAST_RATE_TO_USD,
    MS.VOLUME * COALESCE(LC.RATE_TO_USD, 1) AS TOTAL_VOLUME_TO_USD
FROM MONEY_SUM MS
    LEFT JOIN "user" USR ON USR.ID = MS.USER_ID
    LEFT JOIN LATEST_CURRENCY LC ON LC.ID = MS.CURRENCY_ID
ORDER BY 1 DESC,
    2,
    3;