SELECT
	P1.NAME AS PERSON_NAME1,
	P2.NAME AS PERSON_NAME2,
	P1.ADDRESS AS COMMON_ADDRESS
FROM PERSON AS P1
	CROSS JOIN PERSON AS P2
WHERE P1.ID > P2.ID AND P1.ADDRESS = P2.ADDRESS
ORDER BY 1, 2, 3;