INSERT INTO CURRENCY
VALUES (100, 'EUR', 0.85, '2022-01-01 13:29');
INSERT INTO CURRENCY
VALUES (100, 'EUR', 0.79, '2022-01-08 13:29');
-----
SELECT COALESCE(USR.NAME, 'not defined') AS NAME,
    COALESCE(USR.LASTNAME, 'not defined') AS LASTNAME,
    CY.NAME AS CURRENCY_NAME,
    BAL.MONEY * CY.RATE_TO_USD AS CURRENCY_IN_USD
FROM BALANCE BAL
    LEFT JOIN "user" USR ON BAL.USER_ID = USR.ID
    JOIN CURRENCY CY ON BAL.CURRENCY_ID = CY.ID
    AND CY.UPDATED = COALESCE(
        (
            SELECT MAX(CURRENCY.UPDATED)
            FROM CURRENCY
            WHERE BAL.UPDATED > CURRENCY.UPDATED
                AND CY.ID = CURRENCY.ID
        ),
        (
            SELECT MIN(CURRENCY.UPDATED)
            FROM CURRENCY
            WHERE BAL.UPDATED < CURRENCY.UPDATED
                AND CY.ID = CURRENCY.ID
        )
    )
ORDER BY 1 DESC,
    2,
    3;