SELECT PIZZERIA.NAME AS PIZZERIA_NAME
FROM PERSON_VISITS
    JOIN PIZZERIA ON PIZZERIA.ID = PERSON_VISITS.PIZZERIA_ID
WHERE PERSON_ID = 2
    AND VISIT_DATE NOT IN (
        SELECT ORDER_DATE
        FROM PERSON_ORDER
    );