CREATE FUNCTION FNC_PERSON_VISITS_AND_EATS_ON_DATE (
    IN PPERSON VARCHAR DEFAULT 'Dmitriy',
    PPRICE NUMERIC DEFAULT 500,
    PDATE DATE DEFAULT '2022-01-08'
) RETURNS TABLE (PIZZERIA_NAME VARCHAR) AS $$ BEGIN RETURN QUERY
SELECT PIZZERIA.NAME AS PIZZERIA_NAME
FROM PIZZERIA
    JOIN MENU ON MENU.PIZZERIA_ID = PIZZERIA.ID
    JOIN PERSON_VISITS ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
    JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
WHERE PERSON.NAME = PPERSON
    AND MENU.PRICE < PPRICE
    AND PERSON_VISITS.VISIT_DATE = PDATE;
END $$ LANGUAGE PLPGSQL;
-----
SELECT *
FROM FNC_PERSON_VISITS_AND_EATS_ON_DATE (PPRICE := 800);
SELECT *
FROM FNC_PERSON_VISITS_AND_EATS_ON_DATE (
        PPERSON := 'Anna',
        PPRICE := 1300,
        PDATE := '2022-01-01'
    );