SELECT NAME FROM PERSON
	JOIN PERSON_ORDER ON PERSON_ORDER.PERSON_ID = PERSON.ID
	JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
WHERE PIZZA_NAME IN ('cheese pizza', 'pepperoni pizza') AND GENDER = 'female'
GROUP BY NAME
HAVING COUNT(NAME) >= 2;