SELECT NAME FROM PERSON_ORDER
	JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
	JOIN MENU ON MENU.ID = PERSON_ORDER.MENU_ID
WHERE GENDER = 'male'
	AND ADDRESS IN ('Moscow', 'Samara')
	AND PIZZA_NAME IN ('pepperoni pizza', 'mushroom pizza')
ORDER BY 1 DESC;