CREATE FUNCTION FNC_PERSONS_FEMALE () RETURNS TABLE (
    ID BIGINT,
    NAME VARCHAR,
    AGE INTEGER,
    GENDER VARCHAR,
    ADDRESS VARCHAR
) AS $$(
    SELECT *
    FROM PERSON
    WHERE GENDER = 'female'
) $$ LANGUAGE SQL;
-----
CREATE FUNCTION FNC_PERSONS_MALE () RETURNS TABLE (
    ID BIGINT,
    NAME VARCHAR,
    AGE INTEGER,
    GENDER VARCHAR,
    ADDRESS VARCHAR
) AS $$(
    SELECT *
    FROM PERSON
    WHERE GENDER = 'male'
) $$ LANGUAGE SQL;
-----
SELECT *
FROM FNC_PERSONS_FEMALE ();
SELECT *
FROM FNC_PERSONS_MALE ();