SELECT M1.PIZZA_NAME AS PIZZA_NAME,
    P1.NAME AS PIZZERIA_NAME_1,
    P2.NAME AS PIZZERIA_NAME_2,
    M1.PRICE AS PRICE
FROM MENU AS M1
    JOIN MENU AS M2 ON M2.PRICE = M1.PRICE
    JOIN PIZZERIA AS P1 ON P1.ID = M1.PIZZERIA_ID
    JOIN PIZZERIA AS P2 ON P2.ID = M2.PIZZERIA_ID
WHERE M1.ID > M2.ID
    AND M1.PIZZA_NAME = M2.PIZZA_NAME
ORDER BY 1;