SELECT ADDRESS,
    ROUND(MAX(AGE) - MIN(AGE) / MAX(AGE::NUMERIC), 2) AS FORMULA,
    ROUND(AVG(AGE), 2) AS AVERAGE,
    CASE
        WHEN ROUND(MAX(AGE) - MIN(AGE) / MAX(AGE), 2) > ROUND(AVG(AGE), 2) THEN 'true'
        ELSE 'false'
    END COMPARISON
FROM PERSON
GROUP BY ADDRESS
ORDER BY 1;