CREATE VIEW V_PRICE_WITH_DISCOUNT AS
SELECT NAME,
    PIZZA_NAME,
    PRICE,
    CAST((PRICE - PRICE * 0.1) AS INT) AS DISCOUNT_PRICE
FROM MENU
    JOIN PERSON_ORDER ON PERSON_ORDER.MENU_ID = MENU.ID
    JOIN PERSON ON PERSON.ID = PERSON_ORDER.PERSON_ID
ORDER BY 1,
    2;