(
    SELECT P.NAME AS NAME,
        COUNT(P.NAME) AS COUNT,
        'order' AS ACTION_TYPE
    FROM PERSON_ORDER PO
        JOIN MENU M ON M.ID = PO.MENU_ID
        JOIN PIZZERIA P ON P.ID = M.PIZZERIA_ID
    GROUP BY P.NAME
    ORDER BY 2 DESC
    LIMIT 3
)
UNION
(
    SELECT P.NAME AS NAME,
        COUNT(P.NAME) AS COUNT,
        'visit' AS ACTION_TYPE
    FROM PERSON_VISITS PV
        JOIN PIZZERIA P ON P.ID = PV.PIZZERIA_ID
    GROUP BY P.NAME
    ORDER BY 2 DESC
    LIMIT 3
)
ORDER BY 3,
    2 DESC;